### ISSUE TITLE
RTL Not Supported as it should

### ISSUE THREAD

**Issue by eslamsa3ed** [creativetimofficial/ct-material-dashboard-pro-laravel-livewire#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Using bootstrap RTL classes should works 
 
# Current Behavior

bootstrap RTL classes didn't work even in the RTL example page

## Steps to Reproduce

1. Add dir="rtl" and lang="ar" attributes on HTML tag
2. add class="rtl" to body tag
3. use bootstrap classes like end-0 
4- check the styles rendered on the browser 

## Context

RTL is not supported as it should there is only one fixed static RTL page but if we actually set dir to RTL in all other pages most of the components and elements style will be broken

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products. 

We apologies for the big delay in the response. 

Has the issue been resolved or is there something we can help you with? 

Thank you
